controller_list:
  - name: fake_left_hip_knee_1_controller
    joints:
      - joint_left_h1
      - joint_left_k1
  - name: fake_left_hip_knee_2_controller
    joints:
      - joint_left_h2
      - joint_left_k2
  - name: fake_Right_hip_knee_1_controller
    joints:
      - joint_right_h1
      - joint_right_k1
  - name: fake_Right_hip_knee_2_controller
    joints:
      - joint_right_h2
      - joint_right_k2
initial:  # Define initial robot poses.
  - group: left_hip_knee_1
    pose: left_hip_knee_1_fwd
  - group: left_hip_knee_2
    pose: left_hip_knee_2_fwd
  - group: Right_hip_knee_1
    pose: right_hip_knee_2_fwd
  - group: Right_hip_knee_2
    pose: right_hip_knee_2